:)
some new text

const foo = () =>{
    const x = 'ACTIVITY.AFSLUTSAGBOLIGRAADGIVER.BORGERMUNDTLIGTMEDDELT.LABELB';
}
"ACTIVITY.AFSLUTSAGBOLIGRAADGIVER.BORGERMUNDTLIGTMEDDELT.LABELC"
jjkhjhkjklmlkmlkm

